In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_excel("./sales_data/1.xlsx")

files = [file for file in os.listdir('./sales_data')]

all_months_data = pd.DataFrame()

for file in files:
    df = pd.read_excel("./sales_data/"+file)
    all_months_data = pd.concat([all_months_data, df])
    
all_months_data.to_excel("all_data.xlsx", index=False)

In [3]:
all_data =pd.read_excel("all_data.xlsx" )
all_data.head()

,Order No,Owner 1,Owner 2,Owner 3,AreaSalesManager,Reporting Manager,User,User Rank,Distributor,Region,...,No Sales Reason Category,No Sales Reason,Order Remark To Distributor,Outlets Type,Outlet Channel,Focused Outlet,Asset Present,Type Of Visit,Expected Delivery Date,Employee DOJ (HIN)
0,176620041,Prakash Shrestha,Arjun Adhakari,Dipendra Shrestha,Suresh Nepal,Subarna Shrestha,Babulal Chhettri,Employee,Syangja Kafle Suppliers,Nepal,...,NaN,NaN,NaN,Kirana,GT,No,No,Physical,NaT,NaN
1,176620041,Prakash Shrestha,Arjun Adhakari,Dipendra Shrestha,Suresh Nepal,Subarna Shrestha,Babulal Chhettri,Employee,Syangja Kafle Suppliers,Nepal,...,NaN,NaN,NaN,Kirana,GT,No,No,Physical,NaT,NaN
2,176620047,Prakash Shrestha,Arjun Adhakari,Dipendra Shrestha,Suresh Nepal,Subarna Shrestha,Babulal Chhettri,Employee,Syangja Kafle Suppliers,Nepal,...,NaN,NaN,NaN,Department Store,GT,No,No,Physical,NaT,NaN
3,176620053,Prakash Shrestha,Arjun Adhakari,Dipendra Shrestha,Suresh Nepal,Subarna Shrestha,Babulal Chhettri,Employee,Syangja Kafle Suppliers,Nepal,...,COMPETITOR RELATED ISSUE,Stock Dumping,NaN,Kirana,GT,No,No,Physical,NaT,NaN
4,176623736,Prakash Shrestha,Arjun Adhakari,Dipendra Shrestha,Suresh Nepal,Subarna Shrestha,Govinda Ghimire,Employee,Syangja Kafle Suppliers,Nepal,...,NaN,NaN,NaN,Kirana,GT,No,No,Physical,NaT,NaN

In [4]:
df.columns

Index(['Order No', 'Owner 1 ', 'Owner 2 ', 'Owner 3 ', 'AreaSalesManager ',
       'Reporting Manager', 'User ', 'User Rank', 'Employee DOJ (HIN)',
       'Distributor ', 'Region ', 'Zone ', 'Territory ', 'Beats ',
       'Outlets Name', 'Owners Name', 'Owners No', 'Address', 'SubCity',
       'Market', 'City', 'State', 'Outlets Created On', 'Order Date', 'Time',
       'Primary Category', 'Secondary Category', 'Product', 'Qty (Std Unit)',
       'Standard Unit', 'Qty (Unit)', 'Unit', 'Price', 'Sale Value',
       'Net Value', 'No Sales Reason Category', 'No Sales Reason',
       'Outlets Type', 'Outlet Channel', 'Focused Outlet', 'Asset Present',
       'Type Of Visit'],
      dtype='object')

In [5]:
df.drop(['Order No', 'Owner 1 ', 'Owner 2 ', 'Owner 3 ', 'AreaSalesManager ',
       'Reporting Manager', 'User Rank', 'Employee DOJ (HIN)',
       'Region ', 'Zone ', 'Territory ', 'Owners No', 'Address', 'SubCity',
        'Primary Category', 
       'Standard Unit',  'Sale Value', 'Outlet Channel', 'Focused Outlet', 'Asset Present',
       'Type Of Visit' ], axis=1, inplace = True)

In [6]:
df.head()

,User,Distributor,Beats,Outlets Name,Owners Name,Market,City,State,Outlets Created On,Order Date,...,Secondary Category,Product,Qty (Std Unit),Qty (Unit),Unit,Price,Net Value,No Sales Reason Category,No Sales Reason,Outlets Type
0,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,100 Ml,Strawberry-100 Ml,1.0,18.0,Pcs,34.62,623.16,NaN,NaN,Hotel & Restaurant
1,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,100 Ml,Vanilla-100 Ml,2.0,36.0,Pcs,34.62,1246.32,NaN,NaN,Hotel & Restaurant
2,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,50 Ml,Butterscotch-50 Ml,1.0,28.0,Pcs,20.00,560.00,NaN,NaN,Hotel & Restaurant
3,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,50 Ml,Strawberry-50 Ml,1.0,28.0,Pcs,20.00,560.00,NaN,NaN,Hotel & Restaurant
4,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,50 Ml,Vanilla-50 Ml,3.0,84.0,Pcs,20.00,1680.00,NaN,NaN,Hotel & Restaurant

In [7]:
all_months_data1 = pd.DataFrame()

all_months_data1 = pd.concat([all_months_data1, df])
    
all_months_data1.to_excel("all_data1.xlsx", index=False)

In [8]:
all_data1 =pd.read_excel("all_data1.xlsx")
all_data1.head()

,User,Distributor,Beats,Outlets Name,Owners Name,Market,City,State,Outlets Created On,Order Date,...,Secondary Category,Product,Qty (Std Unit),Qty (Unit),Unit,Price,Net Value,No Sales Reason Category,No Sales Reason,Outlets Type
0,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,100 Ml,Strawberry-100 Ml,1.0,18.0,Pcs,34.62,623.16,NaN,NaN,Hotel & Restaurant
1,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,100 Ml,Vanilla-100 Ml,2.0,36.0,Pcs,34.62,1246.32,NaN,NaN,Hotel & Restaurant
2,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,50 Ml,Butterscotch-50 Ml,1.0,28.0,Pcs,20.00,560.00,NaN,NaN,Hotel & Restaurant
3,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,50 Ml,Strawberry-50 Ml,1.0,28.0,Pcs,20.00,560.00,NaN,NaN,Hotel & Restaurant
4,Babulal Chhettri,Durga Kirana & Khadina,Durga Kirana (Huwas),Bhagbati Hotel & Restaurant (I),Chet Prasad Basyal,Paiyan / Aethung / Arthung Bazar,Dhawalagiri,Western Development Region,2020-03-01,2020-03-01,...,50 Ml,Vanilla-50 Ml,3.0,84.0,Pcs,20.00,1680.00,NaN,NaN,Hotel & Restaurant